-- Script was generated by Devart Entity Developer, Version 7.3.193.0
-- Script date 2025. 04. 26. 14:39:45
-- Target Server: SQL Server
-- Server Version: 2022

-- 
-- Creating a table LessonSchedules 
-- 
CREATE TABLE LessonSchedules (
   Id INT NOT NULL IDENTITY,
   LessonNum TINYINT NOT NULL,
   StartTime TIME NOT NULL,
   EndTime TIME NOT NULL,
   CONSTRAINT PK_LessonSchedules PRIMARY KEY (Id),
   CONSTRAINT KEY_LessonSchedules_LessonNum UNIQUE (LessonNum)
)
GO

-- 
-- Creating a table SchoolYears 
-- 
CREATE TABLE SchoolYears (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(50) NOT NULL,
   StartDate DATETIME2 NOT NULL,
   EndDate DATETIME2 NOT NULL,
   CONSTRAINT PK_SchoolYears PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Events 
-- 
CREATE TABLE Events (
   Id INT NOT NULL IDENTITY,
   Description NVARCHAR(200) NOT NULL,
   Time DATETIME2 NOT NULL,
   UserId INT NOT NULL,
   Type NVARCHAR(50) NOT NULL,
   CONSTRAINT PK_Events PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Users 
-- 
CREATE TABLE Users (
   Id INT NOT NULL IDENTITY,
   Username NVARCHAR(50) NOT NULL,
   EduId NVARCHAR(12),
   Name NVARCHAR(50) NOT NULL,
   Admin BIT NOT NULL,
   PasswordHash NVARCHAR(255) NOT NULL,
   CONSTRAINT PK_Users PRIMARY KEY (Id),
   CONSTRAINT KEY_Users_Username UNIQUE (Username),
   CONSTRAINT KEY_Users_EduId UNIQUE (EduId)
)
GO

-- 
-- Creating a table Classes 
-- 
CREATE TABLE Classes (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(50) NOT NULL,
   CONSTRAINT PK_Classes PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table Subjects 
-- 
CREATE TABLE Subjects (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(50) NOT NULL,
   CONSTRAINT PK_Subjects PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table LoggedLessons 
-- 
CREATE TABLE LoggedLessons (
   Id INT NOT NULL IDENTITY,
   SubjectId INT NOT NULL,
   TeacherId INT NOT NULL,
   ClassId INT NOT NULL,
   SchoolYearId INT NOT NULL,
   LessonNum TINYINT NOT NULL,
   Date DATETIME2 NOT NULL,
   Topic NVARCHAR(255) NOT NULL,
   CONSTRAINT PK_LoggedLessons PRIMARY KEY (Id),
   CONSTRAINT FK_LoggedLessons_Subjects_0 FOREIGN KEY (SubjectId) REFERENCES Subjects (Id),
   CONSTRAINT FK_LoggedLessons_Users_1 FOREIGN KEY (TeacherId) REFERENCES Users (Id),
   CONSTRAINT FK_LoggedLessons_Classes_2 FOREIGN KEY (ClassId) REFERENCES Classes (Id),
   CONSTRAINT FK_LoggedLessons_SchoolYears_3 FOREIGN KEY (SchoolYearId) REFERENCES SchoolYears (Id),
   CONSTRAINT FK_LoggedLessons_LessonSchedules_4 FOREIGN KEY (LessonNum) REFERENCES LessonSchedules (LessonNum)
)
GO

-- 
-- Creating a table TimetableLessons 
-- 
CREATE TABLE TimetableLessons (
   Id INT NOT NULL IDENTITY,
   SubjectId INT NOT NULL,
   TeacherId INT NOT NULL,
   ClassId INT NOT NULL,
   SchoolYearId INT NOT NULL,
   DayNum TINYINT NOT NULL,
   StartDate DATETIME2 NOT NULL,
   EndDate DATETIME2 NOT NULL,
   LessonNum TINYINT NOT NULL,
   CONSTRAINT PK_TimetableLessons PRIMARY KEY (Id),
   CONSTRAINT FK_TimetableLessons_Classes_0 FOREIGN KEY (ClassId) REFERENCES Classes (Id),
   CONSTRAINT FK_TimetableLessons_LessonSchedules_1 FOREIGN KEY (LessonNum) REFERENCES LessonSchedules (LessonNum),
   CONSTRAINT FK_TimetableLessons_Users_2 FOREIGN KEY (TeacherId) REFERENCES Users (Id),
   CONSTRAINT FK_TimetableLessons_SchoolYears_3 FOREIGN KEY (SchoolYearId) REFERENCES SchoolYears (Id),
   CONSTRAINT FK_TimetableLessons_Subjects_4 FOREIGN KEY (SubjectId) REFERENCES Subjects (Id)
)
GO
