//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 01. 20:48:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Models
{
    public partial class enEvent {

        public enEvent()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public DateTime Time { get; set; }

        public string Type { get; set; }

        public int UserId { get; set; }

        public string Description { get; set; }


        public virtual enUser enUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
