//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 03. 21:32:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Models
{
    public partial class TimetableLesson {

        public TimetableLesson()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int SchoolYearId { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public byte DayNum { get; set; }

        public byte LessonNum { get; set; }

        public int ClassId { get; set; }

        public int SubjectId { get; set; }

        public int TeacherId { get; set; }


        public virtual Class Class { get; set; }


        public virtual BellSchedule BellSchedule { get; set; }


        public virtual User Teacher { get; set; }


        public virtual SchoolYear SchoolYear { get; set; }


        public virtual Subject Subject { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
