//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 03. 21:32:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Models
{
    public partial class Subject {

        public Subject()
        {
            this.LoggedLessons = new List<LoggedLesson>();
            this.TimetableLessons = new List<TimetableLesson>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }


        public virtual IList<LoggedLesson> LoggedLessons { get; set; }


        public virtual IList<TimetableLesson> TimetableLessons { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
