//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 15. 11:35:59
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Models
{
    public partial class enLoggedLesson {

        public enLoggedLesson()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int SubjectId { get; set; }

        public int TeacherId { get; set; }

        public int ClassId { get; set; }

        public int SchoolYearId { get; set; }

        public byte LessonNum { get; set; }

        public DateTime Date { get; set; }

        public virtual enSubject enSubject { get; set; }

        public virtual enUser enUser { get; set; }

        public virtual enClass enClass { get; set; }

        public virtual enSchoolYear enSchoolYear { get; set; }

        public virtual enLessonSchedule enLessonSchedule { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
